# Options for controlling the logger.
logging:
  #logging level
  level: "debug"
  # "console" or "json" are the valid formats
  format: "console"
  #log destination.  "console" just prints to stderr, "file" will print to "./logs/commacloner.log"
  detination: "console"
# The 3Commas API key and secret.
# NOTE you should not need to touch the websocket_url or rest_url.  This are only left as configuration items in the off
# chance 3commas changes their api endpoint
api:
  key: "qwertyu"
  secret: "asdfghjkl"
  websocket_url: "wss://ws.3commas.io/websocket"
  rest_url: "https://api.3commas.io/public/api"
#bot configurations
# this can be an array of 1 to n configurations.  there is no limit
bots:
  -
    id: my_first_mapping
    source:
      bot_id: 1234
    dest:
      bot_id: 5678
    overrides:
      quote_currency: "USD"
      base_currency: ""
      cancelUnavailableDeals: true
      panicSellUnavailableDeals: true
  -
    id: additional_bot
    source:
      bot_id: 4285
    dest:
      bot_id: 8675309
    overrides:
      quote_currency: ""
      base_currency: "USDC"
      cancelUnavailableDeals: false